networks:
  backend_sandbox_network:
    driver: bridge

services:

  postgresql:
    container_name: postgresql-database
    image: postgres
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgresql_user
      POSTGRES_PASSWORD: postgresql_password
      POSTGRES_DB: postgresql_database
      POSTGRES_SCHEMA: backend_schema
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
      - ./initdb/postgresql:/docker-entrypoint-initdb.d
    networks:
      - backend_sandbox_network

  postgresql-backend:
    container_name: postgresql-backend
    image: bellsoft/liberica-openjdk-alpine
    restart: unless-stopped
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgresql:5432/postgresql_database?currentSchema=backend_schema
      DATASOURCE_USERNAME: postgresql_user
      DATASOURCE_PASSWORD: postgresql_password
    volumes:
      - ./postgresql-backend/target:/app
    working_dir: /app
    command: java -jar postgresql-backend-1.0.0-SNAPSHOT.jar
    ports:
      - 8181:8181
    networks:
      - backend_sandbox_network
    depends_on:
      - postgresql
