server:
  port: 8181

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresql_database?currentSchema=backend_schema
    username: postgresql_user
    password: postgresql_password
    type: com.zaxxer.hikari.HikariDataSource

logging:
  pattern:
    console: "%magenta(%d) %highlight(%-5level)[%cyan(%t)] %yellow(%logger{1.}): - %msg%n%throwable"
  level:
    org.springframework: INFO