{
 "title": "RED",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{uri!~\".*\\\\*.*\"},uri)"
    }
   }
  ]
 },
 "panels": [
  { "title": "RED (Rate, Errors, Duration)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "description": "Rate (requests per second) - частота запросов в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_count{uri!~\".*\\\\*.*\", uri=~\"$uri\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Errors (errors per second) - частота ошибок в секунду",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"$uri\", status=~\"4..|5..\"}[1m])",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Duration AVG",
   "type": "timeseries",
   "description": "Duration AVG (second) - средняя длительность запроса (в секундах)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{status!~\"4..|5..\"}[1m])) / sum(rate(http_server_requests_seconds_count{status!~\"4..|5..\"}[1m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (uri)(rate(http_server_requests_seconds_sum{uri!~\".*\\\\*.*\", uri=~\"$uri\", status!~\"4..|5..\"}[1m])) / sum by (uri)(rate(http_server_requests_seconds_count{uri!~\".*\\\\*.*\", uri=~\"$uri\", status!~\"4..|5..\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Duration MAX",
   "type": "timeseries",
   "description": "Duration MAX (second) - максимальная длительность запроса (в секундах)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(http_server_requests_seconds_max)",
     "legendFormat": "Total"
    },
    {
     "expr": "max by(uri, status) (http_server_requests_seconds_max{uri!~\".*\\\\*.*\", uri=~\"$uri\"})",
     "legendFormat": "{{status}} - {{uri}}"
    }
   ]
  }
 ]
}