{
 "title": "USE",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "USE (Utilization, Saturation, Errors)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "CPU Utilization (%) - показывает, насколько загружен CPU. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (cpu))",
     "legendFormat": "core-{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "description": "CPU Load Average - Средняя нагрузка за 1 минуту, за 5 минут, за 15 минут. \nЧем больше количество ядер → тем нужнее перегрузка.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "node_load1" },
    { "expr": "node_load5", "legendFormat": "node_load5" },
    { "expr": "node_load15", "legendFormat": "node_load15" }
   ]
  },
  {
   "title": "RAM Memory Utilization",
   "type": "timeseries",
   "description": "RAM Memory Utilization (%) - процент занятой памяти.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "description": "Swap Usage (%) - показывает использование подкачки (индикатор нехватки RAM)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes))",
     "legendFormat": "host"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "description": "Disk Utilization (%) - процент времени, когда диск был занят.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(node_disk_io_time_seconds_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Saturation (Weighted IO Time)",
   "type": "timeseries",
   "description": "Disk Saturation (Weighted IO Time) - oтносительная длина очереди операций.  Чем больше → тем сильная загрузка.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Throughput (Transmit / Receive)",
   "type": "timeseries",
   "description": "Network Throughput (Transmit / Receive) (B/s) - Пропускная способность интерфейсов.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1m]))",
     "legendFormat": "transmit"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1m]))",
     "legendFormat": "receive"
    }
   ]
  },
  {
   "title": "Network Errors (Transmit Errors / Receive Errors)",
   "type": "timeseries",
   "description": "Network Errors (Transmit Errors / Receive Errors) - ошибки в передаче и приёме данных (возможные проблемы сети или драйвера).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "err/s" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_errs_total[1m]))",
     "legendFormat": "transmit errors"
    },
    {
     "expr": "sum(rate(node_network_receive_errs_total[1m]))",
     "legendFormat": "receive_errors"
    }
   ]
  }
 ]
}